In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy as sp

In [2]:
from sklearn.ensemble import GradientBoostingRegressor

In [3]:
import os
import pickle
import sklearn

# Import data

In [4]:
data_uri = "https://noaadata.apps.nsidc.org/NOAA/G02135/seaice_analysis/Sea_Ice_Index_Daily_Extent_G02135_v3.0.xlsx"

In [6]:
df = pd.read_excel(data_uri, header=0)
df.head(10)

,Unnamed: 0,Unnamed: 1,1978,1979,1980,1981,1982,1983,1984,1985,...,2019,2020,2021,2022,2023,2024,2025,,1981-2010 mean,1981-2010 median
0,January,1,NaN,NaN,14.200,14.256,NaN,14.253,NaN,NaN,...,12.934,13.046,12.711,13.291,12.734,13.206,12.510,NaN,13.778,13.823
1,NaN,2,NaN,14.997,NaN,NaN,14.479,NaN,14.103,14.045,...,12.992,13.072,12.710,13.392,12.724,13.300,12.525,NaN,13.842,13.886
2,NaN,3,NaN,NaN,14.302,14.456,NaN,14.306,NaN,NaN,...,12.980,13.170,12.799,13.354,12.717,13.429,12.524,NaN,13.891,13.884
3,NaN,4,NaN,14.922,NaN,NaN,14.642,NaN,14.237,14.240,...,13.045,13.193,12.834,13.440,12.786,13.449,12.432,NaN,13.930,13.925
4,NaN,5,NaN,NaN,14.414,14.435,NaN,14.494,NaN,NaN,...,13.147,13.166,12.862,13.496,12.841,13.590,12.522,NaN,13.978,14.036
5,NaN,6,NaN,14.929,NaN,NaN,14.880,NaN,14.262,14.406,...,13.316,13.195,12.917,13.573,12.875,13.704,12.665,NaN,14.028,14.139
6,NaN,7,NaN,NaN,14.518,14.689,NaN,14.467,NaN,NaN,...,13.282,13.202,13.024,13.591,12.998,13.879,12.801,NaN,14.091,14.188
7,NaN,8,NaN,14.968,NaN,NaN,14.993,NaN,14.303,14.432,...,13.236,13.295,13.039,13.676,13.205,13.754,12.816,NaN,14.132,14.303
8,NaN,9,NaN,NaN,14.594,14.619,NaN,14.615,NaN,NaN,...,13.458,13.248,13.078,13.668,13.177,13.778,12.922,NaN,14.170,14.310
9,NaN,10,NaN,15.190,NaN,NaN,15.052,NaN,14.387,14.455,...,13.383,13.216,13.179,13.651,13.204,13.885,13.010,NaN,14.196,14.240

In [7]:
df.rename(columns={df.columns[0]:"Month", df.columns[1]:"Day"}, inplace=True)

In [8]:
df.head(5)

,Month,Day,1978,1979,1980,1981,1982,1983,1984,1985,...,2019,2020,2021,2022,2023,2024,2025,,1981-2010 mean,1981-2010 median
0,January,1,NaN,NaN,14.200,14.256,NaN,14.253,NaN,NaN,...,12.934,13.046,12.711,13.291,12.734,13.206,12.510,NaN,13.778,13.823
1,NaN,2,NaN,14.997,NaN,NaN,14.479,NaN,14.103,14.045,...,12.992,13.072,12.710,13.392,12.724,13.300,12.525,NaN,13.842,13.886
2,NaN,3,NaN,NaN,14.302,14.456,NaN,14.306,NaN,NaN,...,12.980,13.170,12.799,13.354,12.717,13.429,12.524,NaN,13.891,13.884
3,NaN,4,NaN,14.922,NaN,NaN,14.642,NaN,14.237,14.240,...,13.045,13.193,12.834,13.440,12.786,13.449,12.432,NaN,13.930,13.925
4,NaN,5,NaN,NaN,14.414,14.435,NaN,14.494,NaN,NaN,...,13.147,13.166,12.862,13.496,12.841,13.590,12.522,NaN,13.978,14.036

In [ ]:
df.ffill()

In [9]:
df.Month.ffill(inplace=True)

/tmp/ipykernel_332533/3890864268.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Month.ffill(inplace=True)

# Filter

* Will be using data from 1989 the year from which daily measurements were made

In [10]:
col_list = df.columns.tolist()
col_to_remove = col_list[2:13]
col_to_remove

[1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988]

In [11]:
col_to_include = [elem for elem in col_list if elem not in col_to_remove]
col_to_include

['Month',
 'Day',
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024,
 2025,
 ' ',
 '1981-2010 mean',
 '1981-2010 median']

In [12]:
df_filtered = df[col_to_include].copy()
df_filtered.head(5)

,Month,Day,1989,1990,1991,1992,1993,1994,1995,1996,...,2019,2020,2021,2022,2023,2024,2025,,1981-2010 mean,1981-2010 median
0,January,1,14.261,14.319,13.634,14.069,14.035,14.095,14.145,13.804,...,12.934,13.046,12.711,13.291,12.734,13.206,12.510,NaN,13.778,13.823
1,January,2,14.313,14.384,13.831,14.092,14.141,14.110,14.258,13.818,...,12.992,13.072,12.710,13.392,12.724,13.300,12.525,NaN,13.842,13.886
2,January,3,14.402,14.283,13.847,14.141,14.250,14.042,14.335,13.786,...,12.980,13.170,12.799,13.354,12.717,13.429,12.524,NaN,13.891,13.884
3,January,4,14.417,14.321,13.858,14.072,14.255,14.168,14.288,13.791,...,13.045,13.193,12.834,13.440,12.786,13.449,12.432,NaN,13.930,13.925
4,January,5,14.381,14.303,13.872,14.185,14.266,14.231,14.304,13.839,...,13.147,13.166,12.862,13.496,12.841,13.590,12.522,NaN,13.978,14.036

## Dropping Feb 29th for the sake of demo

In [13]:
df_filtered.drop(columns=[df_filtered.columns[39]], inplace=True)

In [14]:
df_filtered = df_filtered[~((df_filtered.Month == "February") & (df_filtered.Day==29))]
df_filtered.head(5)

,Month,Day,1989,1990,1991,1992,1993,1994,1995,1996,...,2018,2019,2020,2021,2022,2023,2024,2025,1981-2010 mean,1981-2010 median
0,January,1,14.261,14.319,13.634,14.069,14.035,14.095,14.145,13.804,...,12.484,12.934,13.046,12.711,13.291,12.734,13.206,12.510,13.778,13.823
1,January,2,14.313,14.384,13.831,14.092,14.141,14.110,14.258,13.818,...,12.600,12.992,13.072,12.710,13.392,12.724,13.300,12.525,13.842,13.886
2,January,3,14.402,14.283,13.847,14.141,14.250,14.042,14.335,13.786,...,12.634,12.980,13.170,12.799,13.354,12.717,13.429,12.524,13.891,13.884
3,January,4,14.417,14.321,13.858,14.072,14.255,14.168,14.288,13.791,...,12.724,13.045,13.193,12.834,13.440,12.786,13.449,12.432,13.930,13.925
4,January,5,14.381,14.303,13.872,14.185,14.266,14.231,14.304,13.839,...,12.834,13.147,13.166,12.862,13.496,12.841,13.590,12.522,13.978,14.036

In [15]:
len(df_filtered)

365

# Clean

## 2024 has null values

In [16]:
df_filtered[[2024]].isna().sum()

2024    7
dtype: int64

In [17]:
fill_value = (df_filtered.loc[254, 2024] + df_filtered.loc[261, 2024] )/2
fill_value

np.float64(4.300000000000001)

In [18]:
df_filtered.loc[255:261, 2024].fillna(value=fill_value, inplace=True)
df_filtered.isna().sum()

/tmp/ipykernel_332533/1171532009.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_filtered.loc[255:261, 2024].fillna(value=fill_value, inplace=True)

Month                 0
Day                   0
1989                  0
1990                  0
1991                  0
1992                  0
1993                  0
1994                  0
1995                  0
1996                  0
1997                  0
1998                  0
1999                  0
2000                  0
2001                  0
2002                  0
2003                  0
2004                  0
2005                  0
2006                  0
2007                  0
2008                  0
2009                  0
2010                  0
2011                  0
2012                  0
2013                  0
2014                  0
2015                  0
2016                  0
2017                  0
2018                  0
2019                  0
2020                  0
2021                  0
2022                  0
2023                  0
2024                  1
2025                338
1981-2010 mean        0
1981-2010 median      0
dtype: int64

# Preprocessing

In [19]:
months = pd.unique(df_filtered.Month)
months

array(['January', 'February', 'March', 'April', 'May', 'June', 'July',
       'August', 'September', 'October', 'November', 'December'],
      dtype=object)

In [20]:
month_day_list = [elem.Month + ' ' + str(elem.Day) for elem in df_filtered[['Month', 'Day']].itertuples()]

In [21]:
month_day_list[:10]

['January 1',
 'January 2',
 'January 3',
 'January 4',
 'January 5',
 'January 6',
 'January 7',
 'January 8',
 'January 9',
 'January 10']

In [22]:
len(month_day_list)

365

In [23]:
start_year = 1989
start_col = df_filtered.columns.tolist().index(start_year)
start_col

2

In [24]:
end_year = 2025
end_col = df_filtered.columns.tolist().index(end_year)
end_col

38

In [25]:
dates = []
values = []
for year in df_filtered.columns[start_col:end_col+1]:

    for elem in df_filtered[["Month", "Day"]].itertuples():
        x = elem.Month + ' ' + str(elem.Day) + ' ' + str(year)
        dates.append(x)
        values.append(df_filtered.loc[elem.Index, year])
        # print(f"x = {elem.Month + ' ' + str(elem.Day) + ' ' + str(year)}")
        # print(f"y = {df_filtered.loc[elem.Index, year]}")

In [26]:
assert len(dates) == len(df_filtered) * (end_col - start_col + 1)

In [27]:
len(dates)

13505

In [28]:
len(values)

13505

## New long table dataframe

In [29]:
df_processed = pd.DataFrame(data=zip(dates, values), columns=["Date", "Value"])
df_processed.head(10)

              Date   Value
0   January 1 1989  14.261
1   January 2 1989  14.313
2   January 3 1989  14.402
3   January 4 1989  14.417
4   January 5 1989  14.381
5   January 6 1989  14.359
6   January 7 1989  14.420
7   January 8 1989  14.548
8   January 9 1989  14.701
9  January 10 1989  14.755

In [30]:
df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13505 entries, 0 to 13504
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    13505 non-null  object
 1   Value   13166 non-null  float64
dtypes: float64(1), object(1)
memory usage: 211.1+ KB

## Need to remove 2025 null values

In [31]:
df_processed.tail(10)

                   Date  Value
13495  December 22 2025    NaN
13496  December 23 2025    NaN
13497  December 24 2025    NaN
13498  December 25 2025    NaN
13499  December 26 2025    NaN
13500  December 27 2025    NaN
13501  December 28 2025    NaN
13502  December 29 2025    NaN
13503  December 30 2025    NaN
13504  December 31 2025    NaN

In [32]:
df_processed.dropna(inplace=True)
df_processed.tail(10)

                  Date   Value
13157  January 18 2025  13.259
13158  January 19 2025  13.365
13159  January 20 2025  13.376
13160  January 21 2025  13.491
13161  January 22 2025  13.417
13162  January 23 2025  13.495
13163  January 24 2025  13.547
13164  January 25 2025  13.578
13165  January 26 2025  13.572
13166  January 27 2025  13.648

In [33]:
df_processed.isna().sum()

Date     0
Value    0
dtype: int64

## Converting string date to pd.datetime64

In [34]:
df_processed[['Date']] = df_processed[['Date']].apply(lambda x:pd.to_datetime(x))

In [35]:
df_processed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13166 entries, 0 to 13166
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    13166 non-null  datetime64[ns]
 1   Value   13166 non-null  float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 308.6 KB

## Converting datetime to trignometric values

In [36]:
df_processed['time_cos'] = np.cos(df_processed['Date'].map(lambda x: x.value))

In [37]:
df_processed.head(5)

        Date   Value  time_cos
0 1989-01-01  14.261 -0.575545
1 1989-01-02  14.313 -0.842320
2 1989-01-03  14.402  0.501364
3 1989-01-04  14.417  0.886474
4 1989-01-05  14.381 -0.423295

In [38]:
df_processed['time_sin'] = np.sin(df_processed['Date'].map(lambda x: x.value))
df_processed.head(5)

        Date   Value  time_cos  time_sin
0 1989-01-01  14.261 -0.575545 -0.817770
1 1989-01-02  14.313 -0.842320  0.538977
2 1989-01-03  14.402  0.501364  0.865236
3 1989-01-04  14.417  0.886474 -0.462778
4 1989-01-05  14.381 -0.423295 -0.905992

# Gradient Boosting Regressor

## Preparing data

In [39]:
df_processed.head(5)

        Date   Value  time_cos  time_sin
0 1989-01-01  14.261 -0.575545 -0.817770
1 1989-01-02  14.313 -0.842320  0.538977
2 1989-01-03  14.402  0.501364  0.865236
3 1989-01-04  14.417  0.886474 -0.462778
4 1989-01-05  14.381 -0.423295 -0.905992

In [40]:
len(df_processed)

13166

In [41]:
train_length = int(0.8*len(df_processed))
train_length

10532

In [42]:
train_data = df_processed.iloc[:train_length, :]

In [43]:
test_data = df_processed.iloc[train_length:, :]

### Train data

In [44]:
X_train = train_data[['time_cos', 'time_sin', 'Value']].to_numpy()[:-1]

In [45]:
y_train = train_data.Value.to_numpy()[1:]
y_train[-2:]

array([8.882, 8.992])

In [46]:
assert len(X_train) == len(y_train)

### Test data

In [47]:
X_test = test_data[['time_cos', 'time_sin', 'Value']].to_numpy()[:-1]

In [48]:
y_test = test_data.Value.to_numpy()[1:]

## Model training

In [49]:
gbr = GradientBoostingRegressor(loss = 'squared_error', n_estimators=1000)

In [50]:
gbr.fit(X_train, y_train)

GradientBoostingRegressor(n_estimators=1000)

In [51]:
gbr.score(X_train, y_train)

0.999531430000691

In [52]:
gbr.score(X_test, y_test)

0.99926642673597

In [53]:
y_train_predict = gbr.predict(X_train)

In [54]:
y_test_predict = gbr.predict(X_test)

### 5th percentile

In [55]:
gbr_5 = GradientBoostingRegressor(loss = 'quantile', alpha=0.05, n_estimators=1000)

In [56]:
gbr_5.fit(X_train, y_train)

GradientBoostingRegressor(alpha=0.05, loss='quantile', n_estimators=1000)

In [57]:
gbr_5.score(X_train, y_train)

0.9976401892652527

In [58]:
gbr_5.score(X_test, y_test)

0.9978122555379936

In [59]:
y_train_predict_5 = gbr_5.predict(X_train)

In [60]:
y_test_predict_5 = gbr_5.predict(X_test)

### 95th percentile

In [61]:
gbr_95 = GradientBoostingRegressor(loss = 'quantile', alpha=0.95, n_estimators=1000)

In [62]:
gbr_95.fit(X_train, y_train)

GradientBoostingRegressor(alpha=0.95, loss='quantile', n_estimators=1000)

In [63]:
gbr_95.score(X_train, y_train)

0.9972415213385588

In [64]:
gbr_95.score(X_test, y_test)

0.9974525423745764

In [65]:
y_train_predict_95 = gbr_95.predict(X_train)

In [66]:
y_test_predict_95 = gbr_95.predict(X_test)

In [ ]:
pd.Da

# Inference model

In [67]:
def convert_date_func(day:int, month:int, year: int):

    date_entry = f"{day}/{month}/{year}"
    
    to_datetime_obj = pd.to_datetime(date_entry, format="%d/%m/%Y")

    return np.cos(to_datetime_obj.value), np.sin(to_datetime_obj.value)

In [68]:
import sklearn

In [69]:
def inference_model(model_squared_err: sklearn.ensemble._gb.GradientBoostingRegressor,
                    model_5th_quantile: sklearn.ensemble._gb.GradientBoostingRegressor,
                    model_95th_quantile: sklearn.ensemble._gb.GradientBoostingRegressor,
                    day: int,
                    month:int,
                    year:int,
                    previous_value: float
                   ) -> dict:

    x_values_part = convert_date_func(day, month, year)

    X = [[x_values_part[0], x_values_part[1], previous_value]]

    # next days prediction
    prediction = {'Predicted value': model_squared_err.predict(X),
                  '5th percentile':  model_5th_quantile.predict(X),
                  '95th percentile': model_95th_quantile.predict(X)     
                 }

    return prediction

In [70]:
X_train[-1].reshape(1,-1)

array([[-0.13350944,  0.99104754,  8.882     ]])

In [71]:
inference_model(gbr, gbr_5, gbr_95, 1, 1, 1990, 14)

{'Predicted value': array([13.98356879]),
 '5th percentile': array([13.89203049]),
 '95th percentile': array([14.13931672])}

# Saving models

In [72]:
if not os.path.exists("saved_models"):
    os.mkdir("saved_models")

In [73]:
filename = "mse_fit.sav"
pickle.dump(gbr, open(f"./saved_models/{filename}", 'wb'))

### TESTING

In [74]:
test_model = pickle.load(open(f"./saved_models/{filename}", 'rb'))

In [75]:
inference_model(test_model, gbr_5, gbr_95, 1, 1, 1990, 14)

{'Predicted value': array([13.98356879]),
 '5th percentile': array([13.89203049]),
 '95th percentile': array([14.13931672])}

In [76]:
filename = "5th_quantile_fit.sav"
pickle.dump(gbr, open(f"./saved_models/{filename}", 'wb'))

In [77]:
filename = "95th_quantile_fit.sav"
pickle.dump(gbr, open(f"./saved_models/{filename}", 'wb'))